@echo off
:: Master batch file to download TOOL_P.TXT from all machines
:: Generated by NC Tool Analyzer

echo ====================================
echo Downloading TOOL_P.TXT from all machines
echo ====================================

:: Create downloads directory
if not exist "%USERPROFILE%\Desktop\ToolData" mkdir "%USERPROFILE%\Desktop\ToolData"

:: Download from M5
echo Downloading from M5 (10.164.181.22)...
"C:\Program Files (x86)\HEIDENHAIN\TNCremo\TNCCMD.exe" -I10.164.181.22 Get TNC:\TABLE\TOOL_P.TCH "%USERPROFILE%\Desktop\ToolData\M5_TOOL_P.TXT"

:: Download from M3  
echo Downloading from M3 (10.164.181.23)...
"C:\Program Files (x86)\HEIDENHAIN\TNCremo\TNCCMD.exe" -I10.164.181.23 Get TNC:\TABLE\TOOL_P.TCH "%USERPROFILE%\Desktop\ToolData\M3_TOOL_P.TXT"

:: Add more machines as needed...

echo ====================================
echo Downloads complete!
echo Files saved to: %USERPROFILE%\Desktop\ToolData\
echo ====================================
pause